import type { Persona } from "@/types/portal";

/**
 * Mock personas — edit this file to customize account data for SE demos.
 * Swap persona ids via the persona switcher; replace with API data later.
 */
export const personas: Persona[] = [
  {
    id: "alex-rivera",
    role: "patient",
    label: "Alex Rivera",
    description: "Patient managing appointments, lab results, and care tasks",
    avatarInitials: "AR",
    heroGreeting: "Good afternoon, Alex",
    heroSubtext:
      "You have one upcoming visit and two items waiting for your attention.",
    profile: {
      displayName: "Alex Rivera",
      preferredName: "Alex",
      email: "alex.rivera@email.com",
      phone: "(555) 214-8832",
      dateOfBirth: "1988-03-14",
      memberId: "CC-4829103",
      planName: "CareConnect Preferred PPO",
      primaryCareProvider: "Dr. Maya Chen, MD",
      pharmacy: "CareConnect Pharmacy — Westside",
      address: {
        line1: "742 Maple Avenue",
        city: "Portland",
        state: "OR",
        zip: "97205",
      },
      preferences: {
        emailNotifications: true,
        smsReminders: true,
        marketingOptIn: false,
      },
    },
    summary: {
      upcomingAppointments: 1,
      unreadMessages: 3,
      openTasks: 2,
      recentResults: 1,
    },
    notifications: [
      {
        id: "n1",
        title: "Lab results available",
        body: "Your recent lipid panel results are ready to review.",
        createdAt: "2026-07-13T09:15:00Z",
        read: false,
        category: "result",
        href: "/messages",
      },
      {
        id: "n2",
        title: "Visit reminder",
        body: "Annual physical with Dr. Chen is scheduled for Thursday at 10:30 AM.",
        createdAt: "2026-07-12T16:40:00Z",
        read: false,
        category: "appointment",
        href: "/appointments",
      },
      {
        id: "n3",
        title: "Message from care team",
        body: "Dr. Chen replied to your question about medication timing.",
        createdAt: "2026-07-11T14:05:00Z",
        read: false,
        category: "message",
        href: "/messages",
      },
      {
        id: "n4",
        title: "Prescription refill processed",
        body: "Your atorvastatin refill is ready for pickup.",
        createdAt: "2026-07-10T11:20:00Z",
        read: true,
        category: "reminder",
      },
    ],
    appointments: [
      {
        id: "a1",
        title: "Annual Physical Exam",
        provider: "Dr. Maya Chen, MD",
        location: "CareConnect Primary Care — Suite 210",
        startsAt: "2026-07-16T17:30:00Z",
        endsAt: "2026-07-16T18:15:00Z",
        status: "scheduled",
        type: "Primary Care",
        notes: "Please arrive 15 minutes early for vitals.",
      },
      {
        id: "a2",
        title: "Dermatology Consult",
        provider: "Dr. James Okonkwo, MD",
        location: "Specialty Pavilion — Floor 3",
        startsAt: "2026-08-02T19:00:00Z",
        endsAt: "2026-08-02T19:30:00Z",
        status: "scheduled",
        type: "Specialty",
      },
      {
        id: "a3",
        title: "Telehealth Follow-up",
        provider: "Dr. Maya Chen, MD",
        location: "Virtual Visit",
        startsAt: "2026-06-20T15:00:00Z",
        endsAt: "2026-06-20T15:20:00Z",
        status: "completed",
        type: "Telehealth",
      },
    ],
    tasks: [
      {
        id: "t1",
        title: "Complete pre-visit questionnaire",
        description: "Update your medical history before Thursday's visit.",
        dueDate: "2026-07-15",
        priority: "high",
        completed: false,
        href: "/appointments",
      },
      {
        id: "t2",
        title: "Review lab results",
        description: "Acknowledge reviewed lipid panel in Messages.",
        dueDate: "2026-07-14",
        priority: "medium",
        completed: false,
        href: "/messages",
      },
      {
        id: "t3",
        title: "Confirm pharmacy preference",
        description: "Ensure Westside Pharmacy is set as preferred fill location.",
        priority: "low",
        completed: true,
      },
    ],
    activity: [
      {
        id: "act1",
        label: "Viewed lab results",
        detail: "Lipid panel — June 2026",
        occurredAt: "2026-07-13T09:20:00Z",
        category: "Results",
      },
      {
        id: "act2",
        label: "Scheduled appointment",
        detail: "Dermatology consult with Dr. Okonkwo",
        occurredAt: "2026-07-09T18:12:00Z",
        category: "Appointments",
      },
      {
        id: "act3",
        label: "Opened resource",
        detail: "Understanding Cholesterol Levels",
        occurredAt: "2026-07-08T21:45:00Z",
        category: "Resources",
      },
      {
        id: "act4",
        label: "Sent secure message",
        detail: "Medication timing question to Dr. Chen",
        occurredAt: "2026-07-07T13:30:00Z",
        category: "Messages",
      },
    ],
    recommendations: [
      {
        id: "r1",
        title: "Understanding Your Lipid Panel",
        summary:
          "Learn what cholesterol numbers mean and practical steps to support heart health.",
        category: "Heart Health",
        readingTimeMinutes: 5,
        href: "/resources",
      },
      {
        id: "r2",
        title: "How to Prepare for Your Annual Physical",
        summary:
          "A short checklist so you get the most from your upcoming visit with Dr. Chen.",
        category: "Preventive Care",
        readingTimeMinutes: 3,
        href: "/resources",
      },
      {
        id: "r3",
        title: "Medication Refill Tips",
        summary:
          "Avoid gaps in therapy with reminders, preferred pharmacy setup, and auto-refill options.",
        category: "Pharmacy",
        readingTimeMinutes: 4,
        href: "/resources",
      },
    ],
    alerts: [
      {
        id: "al1",
        title: "Action needed before your visit",
        body: "Complete your pre-visit questionnaire by Wednesday evening.",
        severity: "warning",
        href: "/appointments",
        ctaLabel: "Start questionnaire",
      },
    ],
    resources: [
      {
        id: "res1",
        title: "Member Benefits Guide 2026",
        summary: "Coverage summary for CareConnect Preferred PPO members.",
        category: "Benefits",
        tags: ["plan", "coverage"],
        featured: true,
        href: "/resources",
      },
      {
        id: "res2",
        title: "Telehealth Visits: What to Expect",
        summary: "Setup tips for a smooth virtual appointment.",
        category: "Care Delivery",
        tags: ["telehealth", "visits"],
        href: "/resources",
      },
      {
        id: "res3",
        title: "Heart-Healthy Meal Ideas",
        summary: "Simple weekly recipes recommended by our nutrition team.",
        category: "Wellness",
        tags: ["nutrition", "heart"],
        href: "/resources",
      },
    ],
  },
  {
    id: "jordan-lee",
    role: "caregiver",
    label: "Jordan Lee",
    description: "Caregiver coordinating care for a family member",
    avatarInitials: "JL",
    heroGreeting: "Welcome back, Jordan",
    heroSubtext:
      "Managing care for Evelyn Lee — next visit is Friday with Cardiology.",
    profile: {
      displayName: "Jordan Lee",
      preferredName: "Jordan",
      email: "jordan.lee@email.com",
      phone: "(555) 902-4410",
      dateOfBirth: "1979-11-02",
      memberId: "CC-1192844",
      planName: "CareConnect Family Advantage",
      primaryCareProvider: "Dr. Priya Nair, MD",
      pharmacy: "CareConnect Pharmacy — Riverview",
      address: {
        line1: "18 Harbor Court",
        line2: "Unit B",
        city: "Seattle",
        state: "WA",
        zip: "98109",
      },
      preferences: {
        emailNotifications: true,
        smsReminders: true,
        marketingOptIn: true,
      },
    },
    careRecipients: [
      {
        name: "Evelyn Lee",
        relationship: "Parent",
        memberId: "CC-7721045",
      },
    ],
    summary: {
      upcomingAppointments: 2,
      unreadMessages: 5,
      openTasks: 4,
      recentResults: 2,
    },
    notifications: [
      {
        id: "jn1",
        title: "Care recipient message",
        body: "Cardiology nurse sent instructions for Evelyn's Friday visit.",
        createdAt: "2026-07-13T08:05:00Z",
        read: false,
        category: "message",
        href: "/messages",
      },
      {
        id: "jn2",
        title: "Medication schedule updated",
        body: "Evelyn's evening beta-blocker dose was adjusted by the care team.",
        createdAt: "2026-07-12T19:30:00Z",
        read: false,
        category: "reminder",
      },
      {
        id: "jn3",
        title: "Transportation request confirmed",
        body: "Medical transport booked for Friday 8:45 AM pickup.",
        createdAt: "2026-07-12T10:10:00Z",
        read: true,
        category: "appointment",
        href: "/appointments",
      },
      {
        id: "jn4",
        title: "Authorization approved",
        body: "Echo cardiogram prior authorization is approved.",
        createdAt: "2026-07-11T15:55:00Z",
        read: false,
        category: "system",
      },
      {
        id: "jn5",
        title: "New care plan document",
        body: "Updated congestive heart failure care plan is available.",
        createdAt: "2026-07-10T12:00:00Z",
        read: false,
        category: "result",
        href: "/resources",
      },
    ],
    appointments: [
      {
        id: "ja1",
        title: "Cardiology Follow-up (Evelyn)",
        provider: "Dr. Alan Brooks, MD",
        location: "Heart & Vascular Center — Suite 400",
        startsAt: "2026-07-17T16:00:00Z",
        endsAt: "2026-07-17T16:45:00Z",
        status: "scheduled",
        type: "Specialty",
        notes: "Bring current medication list and blood pressure log.",
      },
      {
        id: "ja2",
        title: "Primary Care Check-in (Jordan)",
        provider: "Dr. Priya Nair, MD",
        location: "CareConnect Primary Care — Riverview",
        startsAt: "2026-07-24T18:30:00Z",
        endsAt: "2026-07-24T19:00:00Z",
        status: "scheduled",
        type: "Primary Care",
      },
      {
        id: "ja3",
        title: "Lab Draw Request (Evelyn)",
        provider: "CareConnect Lab",
        location: "Outpatient Lab — Building A",
        startsAt: "2026-07-14T14:00:00Z",
        endsAt: "2026-07-14T14:20:00Z",
        status: "requested",
        type: "Lab",
      },
    ],
    tasks: [
      {
        id: "jt1",
        title: "Upload blood pressure log",
        description: "Share last week's readings before Friday's cardiology visit.",
        dueDate: "2026-07-16",
        priority: "high",
        completed: false,
      },
      {
        id: "jt2",
        title: "Confirm medication list",
        description: "Verify Evelyn's current prescriptions with the pharmacy.",
        dueDate: "2026-07-15",
        priority: "high",
        completed: false,
      },
      {
        id: "jt3",
        title: "Review care plan updates",
        description: "Read the new CHF care plan document in Resources.",
        dueDate: "2026-07-18",
        priority: "medium",
        completed: false,
        href: "/resources",
      },
      {
        id: "jt4",
        title: "Set medication reminder",
        description: "Enable evening SMS reminder for Evelyn's beta-blocker.",
        priority: "medium",
        completed: false,
        href: "/profile",
      },
    ],
    activity: [
      {
        id: "jact1",
        label: "Confirmed transport",
        detail: "Friday pickup for Evelyn's cardiology visit",
        occurredAt: "2026-07-12T10:12:00Z",
        category: "Appointments",
      },
      {
        id: "jact2",
        label: "Downloaded care plan",
        detail: "CHF management guide",
        occurredAt: "2026-07-11T16:02:00Z",
        category: "Resources",
      },
      {
        id: "jact3",
        label: "Messaged care coordinator",
        detail: "Asked about medication timing change",
        occurredAt: "2026-07-11T09:40:00Z",
        category: "Messages",
      },
    ],
    recommendations: [
      {
        id: "jr1",
        title: "Caregiver Essentials Checklist",
        summary:
          "Stay organized with appointment tracking, medication lists, and emergency contacts.",
        category: "Caregiving",
        readingTimeMinutes: 6,
        href: "/resources",
      },
      {
        id: "jr2",
        title: "Supporting Heart Failure at Home",
        summary:
          "Daily weight checks, sodium guidance, and when to call the care team.",
        category: "Heart Health",
        readingTimeMinutes: 8,
        href: "/resources",
      },
      {
        id: "jr3",
        title: "Navigating Prior Authorizations",
        summary:
          "What to expect and how to follow up when specialists order imaging.",
        category: "Benefits",
        readingTimeMinutes: 4,
        href: "/resources",
      },
    ],
    alerts: [
      {
        id: "jal1",
        title: "Cardiology visit this Friday",
        body: "Bring Evelyn's blood pressure log and updated medication list.",
        severity: "info",
        href: "/appointments",
        ctaLabel: "View visit details",
      },
      {
        id: "jal2",
        title: "Lab request pending",
        body: "Confirm the outpatient lab draw time for Evelyn.",
        severity: "warning",
        href: "/appointments",
        ctaLabel: "Review request",
      },
    ],
    resources: [
      {
        id: "jres1",
        title: "Family Caregiver Portal Guide",
        summary: "Permissions, proxy access, and shared care dashboards.",
        category: "Caregiving",
        tags: ["caregiver", "access"],
        featured: true,
        href: "/resources",
      },
      {
        id: "jres2",
        title: "CHF Daily Monitoring Log",
        summary: "Printable weight and symptom tracker for home use.",
        category: "Heart Health",
        tags: ["heart", "monitoring"],
        href: "/resources",
      },
      {
        id: "jres3",
        title: "Medical Transport Options",
        summary: "Member-covered ride options and how to schedule.",
        category: "Benefits",
        tags: ["transport", "visits"],
        href: "/resources",
      },
    ],
  },
  {
    id: "sam-okafor",
    role: "power-user",
    label: "Sam Okafor",
    description: "Engaged member focused on education, wellness, and reminders",
    avatarInitials: "SO",
    heroGreeting: "Hi Sam — you're on track",
    heroSubtext:
      "Three new learning modules and weekly wellness goals are ready for you.",
    profile: {
      displayName: "Sam Okafor",
      preferredName: "Sam",
      email: "sam.okafor@email.com",
      phone: "(555) 331-7788",
      dateOfBirth: "1994-07-22",
      memberId: "CC-5501928",
      planName: "CareConnect Wellness Plus",
      primaryCareProvider: "Dr. Elena Vargas, DO",
      pharmacy: "CareConnect Pharmacy — Downtown",
      address: {
        line1: "905 Commerce Street",
        city: "Austin",
        state: "TX",
        zip: "78701",
      },
      preferences: {
        emailNotifications: true,
        smsReminders: false,
        marketingOptIn: true,
      },
    },
    summary: {
      upcomingAppointments: 0,
      unreadMessages: 1,
      openTasks: 3,
      recentResults: 0,
    },
    notifications: [
      {
        id: "sn1",
        title: "New wellness challenge",
        body: "July movement challenge starts tomorrow — join to earn rewards.",
        createdAt: "2026-07-13T07:00:00Z",
        read: false,
        category: "reminder",
        href: "/resources",
      },
      {
        id: "sn2",
        title: "Learning path update",
        body: "Module 2 of Stress & Sleep Hygiene is unlocked.",
        createdAt: "2026-07-12T12:25:00Z",
        read: true,
        category: "system",
        href: "/resources",
      },
    ],
    appointments: [
      {
        id: "sa1",
        title: "Dental Cleaning",
        provider: "CareConnect Dental",
        location: "Dental Suite — Level 1",
        startsAt: "2026-08-10T15:00:00Z",
        endsAt: "2026-08-10T15:45:00Z",
        status: "scheduled",
        type: "Dental",
      },
      {
        id: "sa2",
        title: "Nutrition Coaching",
        provider: "Riley Nguyen, RDN",
        location: "Virtual Visit",
        startsAt: "2026-06-28T17:00:00Z",
        endsAt: "2026-06-28T17:30:00Z",
        status: "completed",
        type: "Wellness",
      },
    ],
    tasks: [
      {
        id: "st1",
        title: "Finish stress & sleep module",
        description: "Complete Module 2 to unlock personal tips.",
        dueDate: "2026-07-20",
        priority: "medium",
        completed: false,
        href: "/resources",
      },
      {
        id: "st2",
        title: "Log weekly activity goal",
        description: "Record 150 minutes of moderate activity for the week.",
        dueDate: "2026-07-19",
        priority: "medium",
        completed: false,
      },
      {
        id: "st3",
        title: "Set seasonal flu reminder",
        description: "Add a calendar reminder for fall vaccination season.",
        priority: "low",
        completed: false,
      },
    ],
    activity: [
      {
        id: "sact1",
        label: "Completed module",
        detail: "Stress & Sleep Hygiene — Module 1",
        occurredAt: "2026-07-12T20:15:00Z",
        category: "Learning",
      },
      {
        id: "sact2",
        label: "Joined challenge",
        detail: "June hydration challenge",
        occurredAt: "2026-06-30T08:00:00Z",
        category: "Wellness",
      },
      {
        id: "sact3",
        label: "Bookmarked resource",
        detail: "Mindfulness for Busy Schedules",
        occurredAt: "2026-06-25T22:10:00Z",
        category: "Resources",
      },
    ],
    recommendations: [
      {
        id: "sr1",
        title: "Mindfulness for Busy Schedules",
        summary: "Five-minute practices you can fit between meetings.",
        category: "Mental Wellness",
        readingTimeMinutes: 4,
        href: "/resources",
      },
      {
        id: "sr2",
        title: "Building a Sustainable Movement Habit",
        summary: "How to stay consistent without burning out.",
        category: "Fitness",
        readingTimeMinutes: 7,
        href: "/resources",
      },
      {
        id: "sr3",
        title: "Preventive Screenings by Age",
        summary: "Recommended screenings for adults in their thirties.",
        category: "Preventive Care",
        readingTimeMinutes: 5,
        href: "/resources",
      },
    ],
    alerts: [
      {
        id: "sal1",
        title: "Wellness challenge starts tomorrow",
        body: "Join the July movement challenge to stay on pace with your goals.",
        severity: "success",
        href: "/resources",
        ctaLabel: "Join challenge",
      },
    ],
    resources: [
      {
        id: "sres1",
        title: "Stress & Sleep Learning Path",
        summary: "Three short modules with actionable nightly routines.",
        category: "Mental Wellness",
        tags: ["sleep", "stress"],
        featured: true,
        href: "/resources",
      },
      {
        id: "sres2",
        title: "Member Rewards Catalog",
        summary: "Redeem points for fitness gear and wellness products.",
        category: "Wellness",
        tags: ["rewards"],
        href: "/resources",
      },
      {
        id: "sres3",
        title: "Vaccine Season Planning",
        summary: "When and where to get seasonal immunizations.",
        category: "Preventive Care",
        tags: ["vaccines"],
        href: "/resources",
      },
    ],
  },
];

export const defaultPersonaId = personas[0]?.id ?? "alex-rivera";

export function getPersonaById(id: string): Persona | undefined {
  return personas.find((persona) => persona.id === id);
}

export function getAllPersonas(): Persona[] {
  return personas;
}
